// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQXQuWDa5ni833rtI4k589dhQnCG80oDc',
    appId: '1:705433208893:web:433da5224b343ae9058254',
    messagingSenderId: '705433208893',
    projectId: 'shoeapp-60803',
    authDomain: 'shoeapp-60803.firebaseapp.com',
    storageBucket: 'shoeapp-60803.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUzz6w4mq08mPaMOTEYxraGQdG0DQ_vOo',
    appId: '1:705433208893:android:bee1eae39798cb02058254',
    messagingSenderId: '705433208893',
    projectId: 'shoeapp-60803',
    storageBucket: 'shoeapp-60803.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp3Pz4awgh_BVb88efpicLlkCM0_0zARk',
    appId: '1:705433208893:ios:2336030ee1ecf55b058254',
    messagingSenderId: '705433208893',
    projectId: 'shoeapp-60803',
    storageBucket: 'shoeapp-60803.firebasestorage.app',
    iosBundleId: 'com.example.flutterStructureArchitecture',
  );
}
